### ISSUE TITLE
Transfert to coq-community?

### ISSUE THREAD

**Issue by CohenCyril** [coq-community/CoqEAL#33]
@CoqEAL/coqeal I suggest to transfer this repository to coq-community, this could only increase the visibility and opportunities of maintenance.

**Comment by CohenCyril** [comment]
@maximedenes @mortberg @drouhling do you agree?

**Comment by drouhling** [comment]
Fine by me.

**Comment by mortberg** [comment]
Fine by me as well!

**Comment by CohenCyril** [comment]
@maximedenes you are the only one left, if you approve, I make the transfer request

**Comment by maximedenes** [comment]
I think it is a very good idea.

**Comment by palmskog** [comment]
Let's close this here as well since the transfer is done.
