### ISSUE TITLE
Inclusion of matrix normal forms code into CoqEAL

### ISSUE THREAD

**Issue by palmskog** [coq-community/coqeal#53]
Thanks to porting effort by @ybertot, the [matrix normal/canonical forms](https://github.com/coq-community/matrix_canonical_forms) by Guillaume Cano have been ported to recent Coq and MathComp, and relies on the latest CoqEAL.

However, at around 2,200 lines of code, this is a small library that is not likely to get a lot of maintenance effort. If we instead consolidate the library into CoqEAL, we may be able to conserve resources and provide the results to a wider audience (since CoqEAL is planned to be part of the Coq platform).

What are the tradeoffs?

- The code depends on MathComp real-closed, which is not currently a dependency of CoqEAL. This will add to time to build in CI. On the other hand, real-closed is also planned to be included in the Coq platform.
- The code depends directly on MathComp fingroup, which is nevertheless a dependency of MathComp algebra which CoqEAL already depends on.
- More code to maintain in CoqEAL.

What do you think @proux01 and @ybertot?

This is obviously not a high priority issue, but if you give the go-ahead, I can set up the transfer in the near future. Essentially, we would just archive the matrix canonical forms repo for posterity with a pointer to CoqEAL.

**Comment by proux01** [comment]
Indeed, a large part of coqeal-theory looks like an antichamber of mathcomp.
But that requires some work (I once attempted to move just some results in ssrcomplement.v but no one got time yet to look at it on the mathcomp side https://github.com/math-comp/math-comp/pull/756 ;-) ).

**Comment by palmskog** [comment]
I'm sympathetic to (all?) results eventually ending up in MathComp proper, but I think we are talking a different time scale than just moving the matrix code to CoqEAL. For example, I don't think we want MathComp to depend on or include Paramcoq? In my mind, the best location for Paramcoq would actually be Coq itself. 

It would be nice to see some documented "MathComp inclusion process" to get a sense of what kind of quality and reusability is needed before opening MathComp PRs. I think it has been said before that finmap is the closest in quality to MathComp itself, yet it is planned to live on for quite a while separately, right?

@proux01 I think this should be a straightforward transfer, I will open a CoqEAL PR adding files to `theory` and we can take it from there.
