### ISSUE TITLE
release/update for mathcomp 1.16

### ISSUE THREAD

**Issue by clayrat** [coq-community/coqeal#73]
Currently https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-coqeal/coq-coqeal.1.1.1/opam conflicts with 1.16

**Comment by proux01** [comment]
We first need a release of real-closed. Once we get it, I'll release Coqeal.

**Comment by clayrat** [comment]
I guess multinomials as well? I've opened issues for both of them as well.

**Comment by proux01** [comment]
Well, multinomials is now fine.

**Comment by proux01** [comment]
Finally fixed: https://github.com/coq/opam-coq-archive/pull/2490
