### ISSUE TITLE
Please create a tag for Coq 8.20 in Coq Platform 2025.01

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/coqeal#96]
The Coq team released Coq `8.20.0` on September 3rd, 2024.
The corresponding Coq Platform release `2025.01` should be released before **Jan 31st, 2025**.
It can be delayed in case of difficulties until Feb 28th, 2025, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (2.0.2) **does not work** with Coq `8.20.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI appears to test this project, but has some special handling for your project which makes it difficult to retrieve the commit it tests for your project.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.20, **preferably before Dec 31st, 2024**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before Dec 8th, 2024, it will be included in an early Coq Platform beta release of the for Coq 8.20.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.20~2025.01`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.20~2025.01.sh) which already supports Coq version `8.20.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/449

**Comment by proux01** [comment]
@MSoegtropIMC currently waiting for a release of real-closed compatible with mathcomp 2.3 and I'll then do a release here

**Comment by MSoegtropIMC** [comment]
Thank you for the update! And yes I am aware of the dependencies. The main purpose of this is to know if there are issues expected which likely cannot be fixed until mid of January, so that I can plan for this early. Worst case we have to do a split release with an older complete version of MC and a newer MC with some packages missing (we did this at the MC 1.X to 2.0 transition). But from what I have heard so far, this is very unlikely to be required for MC 2.3.0.

**Comment by MSoegtropIMC** [comment]
@proux01 : I saw that you have created a new tag 2.0.3. Can you please confirm here that this is the tag you would like to see in Coq Platform 2025.01?

**Comment by proux01** [comment]
@MSoegtropIMC yes, 2.0.3 is the good tag for Coq 8.20, sorry I forgot to answer this issue after the release.

**Comment by MSoegtropIMC** [comment]
Thank you! Unfortunately there are issues with the latest tag of real-closed - I will update as soon as this is solved.

**Comment by MSoegtropIMC** [comment]
I updated Coq Platform to use coq-coqeal version 2.0.3 via https://github.com/coq/platform/pull/454 => closing.
